name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Passo 01 - Baixar a base de código
        uses: actions/checkout@v4

      - name: Passo 02 - Autenticação no DockerHub
        uses: docker/login-action@v2.2.0
        with: 
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Passo 03 - Criar a imagem dos Microsserviços
        run: docker build -t seu_usuario_dockerhub/nome_da_imagem:tag .

      - name: Passo 04 - Subir as imagens para o repositório de imagens Docker (Dockerhub)
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push seu_usuario_dockerhub/nome_da_imagem:tag

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Passo 01 - Baixar a base de código
        uses: actions/checkout@v4

      - name: Passo 02 - Criar a imagem dos Microsserviços
        run: |
          docker build -t seu_usuario_dockerhub/nome_da_imagem:latest .

      - name: Passo 03 - Subir as imagens para o repositório de imagens Docker (Dockerhub)
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push seu_usuario_dockerhub/nome_da_imagem:latest
